[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stele_onchain = "B7iJ9rGP5jPFx3XmWPPAxgvxrv2SvVLRuKNq16iUJWKK"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
